# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "centos/7"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
    subconfig.vm.network :forwarded_port, guest: 6443, host: 6444
    config.vm.network :forwarded_port, guest: 80, host: 24888
    #config.vm.network :forwarded_port, guest: 443, host: 54433
    subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
	vb.cpus = "1"
    end
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      subconfig.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
          vb.cpus = "2"
      end
    end
  end

  # Install avahi on all machines
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    setenforce 0
    sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    systemctl disable firewalld; systemctl stop firewalld; systemctl mask firewalld
    yum update -y
    yum install git -y
    yum install epel-release -y
    yum update -y
    yum install -y ansible
    yum install -y python3
  SHELL

end
